import type { Mentor, ScheduleEvent } from "./types";

/**
 * DEMO CONTENT — FICTIONAL. For visual development and automated tests only.
 *
 * Loaded only when SHOW_DEMO_CONTENT=true and never on a Vercel production deploy
 * (see content/index.ts). Every item is flagged `demo: true` and rendered with a
 * "Demo" badge. Names, companies, links and times here are invented.
 */
export const demoEvents: ScheduleEvent[] = [
  {
    id: "demo-customer-discovery-workshop",
    title: "Demo: Customer Discovery Sprint",
    date: "2026-10-01",
    time: { kind: "exact", start: "10:30", end: "12:00" },
    status: "confirmed",
    types: ["workshop"],
    involvement: "supported",
    foundersPick: true,
    organizer: "Demo Organizer Collective",
    location: { kind: "in-person", venue: "Demo Hall", room: "Room 101", address: "123 Example St, Urbana, IL" },
    summary: "Fictional workshop used to preview overlapping events and registration links.",
    description:
      "This is fictional demo content used to preview the schedule layout.\n\nIt overlaps with an office-hours window on purpose so the agenda's overlap treatment is visible.",
    speakers: [{ name: "Casey Example", title: "Demo facilitator", verified: true }],
    topics: ["customer discovery", "interviews"],
    registration: { url: "https://example.com/demo-registration", label: "Register (demo)" },
    sources: [{ label: "Demo source", url: "https://example.com/demo-source", note: "Fictional." }],
    demo: true,
  },
  {
    id: "demo-opening-keynote",
    title: "Demo: Opening Keynote on Building in Public",
    date: "2026-10-01",
    time: { kind: "exact", start: "17:00", end: "18:30" },
    status: "confirmed",
    types: ["talk"],
    involvement: "week",
    foundersPick: false,
    organizer: "Demo Campus Partner",
    location: { kind: "hybrid", venue: "Demo Auditorium", url: "https://example.com/demo-stream" },
    summary: "Fictional keynote to preview hybrid locations and verified speakers.",
    description: "Fictional demo keynote. Not a real event.",
    speakers: [
      { name: "Jamie Placeholder", title: "Founder, Demo Startup", verified: true },
      { name: "Unverified Speaker", title: "Should not render", verified: false },
    ],
    topics: ["building in public", "fundraising"],
    registration: null,
    sources: [{ label: "Demo source", note: "Fictional." }],
    demo: true,
  },
  {
    id: "demo-founder-mixer",
    title: "Demo: Founder Mixer",
    date: "2026-10-01",
    time: { kind: "exact", start: "18:00", end: "19:30" },
    status: "planned",
    statusNote: "Planned — pending venue confirmation (demo).",
    types: ["networking", "social"],
    involvement: "hosted",
    foundersPick: true,
    organizer: "Founders – Illinois Entrepreneurs (demo)",
    location: { kind: "tba", note: "Venue to be announced." },
    summary: "Fictional mixer overlapping the keynote to preview concurrent evening events.",
    description: "Fictional demo event.",
    speakers: [],
    topics: ["networking"],
    registration: null,
    sources: [],
    demo: true,
  },
  {
    id: "demo-remote-ai-talk",
    title: "Demo: Remote Fireside on AI Products",
    date: "2026-10-02",
    time: { kind: "exact", start: "13:00", end: "14:00" },
    status: "confirmed",
    types: ["talk", "panel"],
    involvement: "week",
    foundersPick: false,
    organizer: "Demo Remote Org",
    location: { kind: "virtual", platform: "Zoom", url: "https://example.com/demo-zoom" },
    summary: "Fictional virtual event to preview virtual links.",
    description: "Fictional demo event.",
    speakers: [{ name: "Riley Sample", title: "Operator, Demo AI", verified: true }],
    topics: ["AI", "product"],
    registration: { url: "https://example.com/demo-rsvp" },
    sources: [{ label: "Demo source", url: "https://example.com/demo" }],
    demo: true,
  },
  {
    id: "demo-time-tba-meetup",
    title: "Demo: Hardware Builders Meetup",
    date: "2026-10-02",
    time: { kind: "tba" },
    status: "tentative",
    statusNote: "Tentative — time not announced (demo).",
    types: ["networking"],
    involvement: null,
    foundersPick: false,
    organizer: "Demo Hardware Club",
    location: { kind: "tba" },
    summary: "Fictional event with no announced time.",
    description: "Fictional demo event.",
    speakers: [],
    topics: ["hardware"],
    registration: null,
    sources: [],
    demo: true,
  },
  {
    id: "demo-pitch-practice",
    title: "Demo: Pitch Practice Lab",
    date: "2026-10-03",
    time: { kind: "exact", start: "14:00", end: "16:00" },
    status: "confirmed",
    types: ["pitch", "workshop"],
    involvement: "supported",
    foundersPick: true,
    organizer: "Demo Venture Club",
    location: { kind: "in-person", venue: "Demo Center", room: "Suite 2" },
    summary: "Fictional pitch session overlapping a panel.",
    description: "Fictional demo event.",
    speakers: [],
    topics: ["pitching"],
    registration: { url: "https://example.com/demo-pitch" },
    sources: [],
    demo: true,
  },
  {
    id: "demo-funding-panel",
    title: "Demo: First Funding Panel",
    date: "2026-10-03",
    time: { kind: "exact", start: "15:00", end: "16:00" },
    status: "confirmed",
    types: ["panel"],
    involvement: "week",
    foundersPick: false,
    organizer: "Demo Finance Society",
    location: { kind: "in-person", venue: "Demo Library", room: "Room 66" },
    summary: "Fictional panel overlapping the pitch lab.",
    description: "Fictional demo event.",
    speakers: [],
    topics: ["fundraising"],
    registration: null,
    sources: [],
    demo: true,
  },
  {
    id: "demo-canceled-session",
    title: "Demo: Canceled Breakfast Session",
    date: "2026-10-03",
    time: { kind: "exact", start: "09:00", end: "10:00" },
    status: "canceled",
    statusNote: "Canceled by the organizer (demo).",
    types: ["networking"],
    involvement: "week",
    foundersPick: false,
    organizer: "Demo Breakfast Club",
    location: { kind: "in-person", venue: "Demo Cafe" },
    summary: "Fictional canceled event to preview canceled styling.",
    description: "Fictional demo event.",
    speakers: [],
    topics: [],
    registration: null,
    sources: [],
    demo: true,
  },
];

export const demoMentors: Mentor[] = [
  {
    id: "demo-avery-sample",
    name: "Avery Sample",
    firstName: "Avery",
    role: "Founder (demo)",
    company: "Demo Robotics Co.",
    headshot: null,
    bio: {
      status: "approved",
      value:
        "Avery Sample is a fictional mentor used to preview a complete profile. Avery is not a real person.",
    },
    expertise: {
      status: "approved",
      value: [
        { label: "Hardware prototyping", basis: "Demo — fictional" },
        { label: "Early customer discovery", basis: "Demo — fictional" },
      ],
    },
    askMeAbout: {
      status: "approved",
      value: ["Finding your first ten customers", "Hardware prototyping on a budget", "Deciding when to incorporate"],
    },
    goodFitFor: {
      status: "approved",
      value: ["Students with an early prototype", "Teams deciding what to build first"],
    },
    session: {
      format: "in-person",
      durationMinutes: 25,
      location: "Demo Hall, Room 202",
      sessionCount: "Two sessions",
      confirmed: true,
    },
    availability: [
      {
        id: "demo-avery-2026-10-01-pm",
        date: "2026-10-01",
        time: { kind: "exact", start: "14:00", end: "15:00" },
      },
    ],
    slots: [
      {
        id: "demo-avery-slot-1400",
        windowId: "demo-avery-2026-10-01-pm",
        date: "2026-10-01",
        start: "14:00",
        end: "14:25",
        capacity: 1,
        status: "confirmed",
        format: "in-person",
        location: "Demo Hall, Room 202",
      },
      {
        id: "demo-avery-slot-1430",
        windowId: "demo-avery-2026-10-01-pm",
        date: "2026-10-01",
        start: "14:30",
        end: "14:55",
        capacity: 2,
        status: "confirmed",
        format: "in-person",
        location: "Demo Hall, Room 202",
      },
    ],
    links: [{ label: "Example link (demo)", url: "https://example.com/avery" }],
    acceptingApplications: true,
    sources: [{ label: "Demo source", note: "Fictional." }],
    demo: true,
  },
  {
    id: "demo-jordan-placeholder",
    name: "Jordan Placeholder",
    firstName: "Jordan",
    role: null,
    company: "Example Labs (demo)",
    headshot: null,
    bio: {
      status: "draft",
      value: "DRAFT bio that must never render publicly.",
      note: "Awaiting mentor approval.",
    },
    expertise: {
      status: "draft",
      value: [{ label: "Draft expertise that must never render publicly", basis: "Demo draft" }],
    },
    askMeAbout: {
      status: "draft",
      value: ["Draft topic that must never render publicly"],
      note: "Proposed by organizers; not yet approved by Jordan.",
    },
    goodFitFor: null,
    session: {
      format: "virtual",
      durationMinutes: null,
      location: null,
      sessionCount: null,
      confirmed: false,
      note: "Duration to be confirmed (demo).",
    },
    availability: [
      {
        id: "demo-jordan-2026-10-02-pm",
        date: "2026-10-02",
        time: { kind: "exact", start: "15:00", end: "16:30" },
      },
    ],
    slots: [
      {
        id: "demo-jordan-slot-1500",
        windowId: "demo-jordan-2026-10-02-pm",
        date: "2026-10-02",
        start: "15:00",
        end: "15:30",
        capacity: 1,
        status: "proposed",
        format: "virtual",
      },
    ],
    links: [],
    acceptingApplications: true,
    sources: [{ label: "Demo source", note: "Fictional." }],
    demo: true,
  },
];
